<!DOCTYPE html>
<html lang="en"><head> 
<meta charset="UTF-8">
<meta name="description" content="chess tournament">
<meta name="author" content="www.vegachess.com">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
<title>2026 HBCC Honourable Bob Rookies and Juniors</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="stylenew.css" type="text/css" >
    </head>
<body>
<div class="d-flex flex-column justify-content-between h-100">
 <nav class="navbar navbar-expand-lg fixed-top">
                <div class="container">    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0"><li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Info</a>
<ul class="dropdown-menu">
<li><a class="dropdown-item" href="schedule.php"> Schedule </a></li><li><a class="dropdown-item" href="tourstat.php">Statistics</a></li> </ul></li><li class="nav-item dropdown">   <a class="nav-link" href="index.php" >Players</a>
</li><li class="nav-item"><a class="nav-link " href="pairs2.php" >Pairings</a>
</li><li class="nav-item"><a class="nav-link" href="standings.php" >Standings</a>
</li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tables</a>
<ul class="dropdown-menu"><li><a class="dropdown-item" href="crosstable.php"> Cross table </a></li><li><a class="dropdown-item" href="crosstablescore.php"> Cross table and standings </a></li><li><a class="dropdown-item" href="rankinggroup.php"> Standings by Rtg groups </a></li><li><a class="dropdown-item" href="rankingagegroup.php"> Standings by age groups </a></li><li><a class="dropdown-item" href="rankcat.php"> Standings by title </a></li><li><a class="dropdown-item" href="rankTeams.php"> Rank Teams </a></li><li><a class="dropdown-item" href="summaryFederations.php"> Summary Federations </a></li><li><a class="dropdown-item" href="summaryOrigin.php"> Summary Origin </a></li></ul></li><li class="nav-item"><a class="nav-link" href="games.php" >Games</a>
</li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reports</a>
<ul class="dropdown-menu">          <li><a class="dropdown-item" href="felovar.php">FIDE Rating</a></li>          <li><a class="dropdown-item" href="fideplayercard.php">FIDE Player Card</a></li>           <li><a class="dropdown-item" href="nelovar.php">National rating</a></li>          <li><a class="dropdown-item" href="playercard.php">National Player Card</a></li></ul></li></ul> </div>
</div>
</nav>
 <section id="hero" class="d-flex align-items-center">
                <div class="container-fluid">
                    <div class="row items-center">
                        <div class="col-12">
                            <div class="flex flex-column justify-content-center text-center text-white">			<h1 class="mb-3" style="text-shadow: 2px 2px 4px #000000;" >2026 HBCC Honourable Bob Rookies and Juniors</h1>		    <h5 class="mb-1">HBCC (AUS)</h5>		    <h5> 31/01/2026 - 28/02/2026</h5>   </div>
 </div> 
 </div>
 </div> 
 </section>
 <section id="main" class="pt-3 mb-auto">
                <div class="container-fluid">
                    <div class="row">
                        <div class="d-none d-lg-block col-1 ps-0">
                            <div class="d-flex flex-column w-full overflow-hidden"> </div> </div> <div class="col-12 col-lg-10">
  <div class="d-flex flex-column"> <div class="btn-toolbar mb-4 mt-4 d-flex align-items-center"> 
<h5>Pairing of round 1, at 18:00 of 31/01/2026</h5>
   	<div class="btn-group mx-5"> 
<?php include("pairing.php"); ?>
   	</div>
 </div>
<div class="table-responsive"><table class="table table-sm table-striped"> 
<thead><tr><th>Bo.</th><th>Fed</th><th>White Player</th><th>Pts</th><th>Result</th><th>Pts</th><th>Black Player</th><th>Fed</th></tr></thead><tbody>
<tr> <td>1</td><td><img class="shadow" src="flag/os.png" alt="OS"></td><td class="name"> <span class="idwhite"> 1 </span><span class="notitle male"> </span> <a href="playercard.php#1"> Vignesh,Prajeeth Balaji</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">42 </span><span class="notitle female"> </span> <a href="playercard.php#42"> Gajula,Nishitha</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>2</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 65 </span><span class="notitle male"> </span> <a href="playercard.php#65"> Koppuravuri,Haneesh</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">2 </span><span class="notitle male"> </span> <a href="playercard.php#2"> Li,LiYuan</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>3</td><td><img class="shadow" src="flag/tas.png" alt="TAS"></td><td class="name"> <span class="idwhite"> 3 </span><span class="notitle male"> </span> <a href="playercard.php#3"> Djatschenko,Addison</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">44 </span><span class="notitle male"> </span> <a href="playercard.php#44"> Das,Ayush</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>4</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 45 </span><span class="notitle male"> </span> <a href="playercard.php#45"> Spriggs,Harvey</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">4 </span><span class="notitle male"> </span> <a href="playercard.php#4"> Nowak,Ruben</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>5</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 5 </span><span class="notitle male"> </span> <a href="playercard.php#5"> Nguyen,Lucas</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">46 </span><span class="notitle female"> </span> <a href="playercard.php#46"> Fang,Candice</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>6</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 47 </span><span class="notitle male"> </span> <a href="playercard.php#47"> Kwek,Alexander</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">6 </span><span class="notitle male"> </span> <a href="playercard.php#6"> Ilic,Milan</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>7</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 7 </span><span class="notitle male"> </span> <a href="playercard.php#7"> Ramanathan,Ashwin</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">48 </span><span class="notitle male"> </span> <a href="playercard.php#48"> Goh,Julian</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>8</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 49 </span><span class="notitle male"> </span> <a href="playercard.php#49"> Bodke,Aryan</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">8 </span><span class="notitle male"> </span> <a href="playercard.php#8"> Annapureddy,Dhruthin Reddy</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>9</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 9 </span><span class="notitle male"> </span> <a href="playercard.php#9"> Batyrbekov,Kaisar</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">50 </span><span class="notitle male"> </span> <a href="playercard.php#50"> Kantharaju,Aryan</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>10</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 52 </span><span class="notitle male"> </span> <a href="playercard.php#52"> Bala,Jake</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">10 </span><span class="notitle male"> </span> <a href="playercard.php#10"> Wilson,Andrew</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>11</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 11 </span><span class="notitle male"> </span> <a href="playercard.php#11"> Veginati,Cherish</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">53 </span><span class="notitle male"> </span> <a href="playercard.php#53"> Bala,Neil</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>12</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 54 </span><span class="notitle male"> </span> <a href="playercard.php#54"> Boxshall,Logan</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">12 </span><span class="notitle male"> </span> <a href="playercard.php#12"> Yendru,Srikrishna</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>13</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 13 </span><span class="notitle male"> </span> <a href="playercard.php#13"> Wilkinson,Greg</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">55 </span><span class="notitle male"> </span> <a href="playercard.php#55"> Chawla,Namish</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>14</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 56 </span><span class="notitle male"> </span> <a href="playercard.php#56"> Daffey,Callum</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">14 </span><span class="notitle male"> </span> <a href="playercard.php#14"> Ahmad,Ihtiram</a></td><td><img class="shadow" src="flag/os.png" alt="OS"></td></tr>
<tr> <td>15</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 15 </span><span class="notitle male"> </span> <a href="playercard.php#15"> Ashok,Arjun</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">57 </span><span class="notitle male"> </span> <a href="playercard.php#57"> Filippone,Noah</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>16</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 58 </span><span class="notitle female"> </span> <a href="playercard.php#58"> Goh,Daphne</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">16 </span><span class="notitle male"> </span> <a href="playercard.php#16"> Balaji,Sai Sivesh</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>17</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 17 </span><span class="notitle male"> </span> <a href="playercard.php#17"> Batyrbekov,Aidan</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">59 </span><span class="notitle female"> </span> <a href="playercard.php#59"> Haller,Annabelle</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>18</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 60 </span><span class="notitle male"> </span> <a href="playercard.php#60"> Jyothi Nikhil,Vihaan</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">18 </span><span class="notitle male"> </span> <a href="playercard.php#18"> Wei,Andrew</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>19</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 19 </span><span class="notitle male"> </span> <a href="playercard.php#19"> Huang,Michael</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">61 </span><span class="notitle female"> </span> <a href="playercard.php#61"> Kaur,Arveen</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>20</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 62 </span><span class="notitle male"> </span> <a href="playercard.php#62"> Khanna,Daksh</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">20 </span><span class="notitle male"> </span> <a href="playercard.php#20"> Rawat,Vivaan</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>21</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 21 </span><span class="notitle male"> </span> <a href="playercard.php#21"> Ruaya,Rohan</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">63 </span><span class="notitle female"> </span> <a href="playercard.php#63"> Kommina,Bhavishya</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>22</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 64 </span><span class="notitle male"> </span> <a href="playercard.php#64"> Kommina,Lakshmi Srinivas</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">22 </span><span class="notitle male"> </span> <a href="playercard.php#22"> Jagannathan,Shashvath</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>23</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 23 </span><span class="notitle male"> </span> <a href="playercard.php#23"> Vemula,Thamoghna</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">66 </span><span class="notitle female"> </span> <a href="playercard.php#66"> Madduluri,Advaitha</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>24</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 67 </span><span class="notitle male"> </span> <a href="playercard.php#67"> Mallajosyula,Srivaths</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">24 </span><span class="notitle male"> </span> <a href="playercard.php#24"> Nema,Nivaan</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>25</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 25 </span><span class="notitle male"> </span> <a href="playercard.php#25"> Singh,Abhyuday</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">68 </span><span class="notitle male"> </span> <a href="playercard.php#68"> Martin,Dion</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>26</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 37 </span><span class="notitle male"> </span> <a href="playercard.php#37"> Yegnavajjula,Aryan Srivatsav</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">26 </span><span class="notitle male"> </span> <a href="playercard.php#26"> Jyothi Nikhil,Neev</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>27</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 27 </span><span class="notitle male"> </span> <a href="playercard.php#27"> Guggilla,Krithvik</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">70 </span><span class="notitle male"> </span> <a href="playercard.php#70"> Milne,Hamish</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>28</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 71 </span><span class="notitle male"> </span> <a href="playercard.php#71"> Northe-McCulloch, Jack</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">29 </span><span class="notitle male"> </span> <a href="playercard.php#29"> Yendru,Sriram</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>29</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 31 </span><span class="notitle male"> </span> <a href="playercard.php#31"> Shaiek,Nihal</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">51 </span><span class="notitle male"> </span> <a href="playercard.php#51"> Bacon,Levi</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>30</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 74 </span><span class="notitle male"> </span> <a href="playercard.php#74"> Rivero,Adam</a> </td><td>0</td><td class="result">½ - ½</td><td>0</td><td class="name"><span class="idblack">32 </span><span class="notitle male"> </span> <a href="playercard.php#32"> Subhash,Ryan</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>31</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 33 </span><span class="notitle male"> </span> <a href="playercard.php#33"> Goh,Nicholas</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">75 </span><span class="notitle male"> </span> <a href="playercard.php#75"> Samraat,Aayush</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>32</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 76 </span><span class="notitle male"> </span> <a href="playercard.php#76"> Siripurapu,Jatin Aarush</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">34 </span><span class="notitle female"> </span> <a href="playercard.php#34"> Kaur,Mishleen</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>33</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 35 </span><span class="notitle female"> </span> <a href="playercard.php#35"> Venkat,Nyra</a> </td><td>0</td><td class="result">½ - ½</td><td>0</td><td class="name"><span class="idblack">77 </span><span class="notitle male"> </span> <a href="playercard.php#77"> Tan,Lucas</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>34</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 78 </span><span class="notitle male"> </span> <a href="playercard.php#78"> Wang,Evan</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">36 </span><span class="notitle male"> </span> <a href="playercard.php#36"> Balamurugan,Soorya</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>35</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 38 </span><span class="notitle male"> </span> <a href="playercard.php#38"> Manoj,Dev</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">79 </span><span class="notitle male"> </span> <a href="playercard.php#79"> Watson,Jacob</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>36</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 80 </span><span class="notitle male"> </span> <a href="playercard.php#80"> Wei,Charlie</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">39 </span><span class="notitle female"> </span> <a href="playercard.php#39"> Husain,Lamiah</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>37</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 40 </span><span class="notitle male"> </span> <a href="playercard.php#40"> Gadham,Aarya Subramanya</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">81 </span><span class="notitle female"> </span> <a href="playercard.php#81"> Yadav,Riyaan</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>38</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 82 </span><span class="notitle male"> </span> <a href="playercard.php#82"> Yang,Aiden</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">41 </span><span class="notitle male"> </span> <a href="playercard.php#41"> Barar,Ridam</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>39</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 30 </span><span class="notitle female"> </span> <a href="playercard.php#30"> Prince,Aliza</a> </td><td>0</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td></tr>
<tr> <td>40</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 73 </span><span class="notitle male"> </span> <a href="playercard.php#73"> Pradeep,Mayukh</a> </td><td>0</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td></tr>
<tr> <td>41</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 43 </span><span class="notitle male"> </span> <a href="playercard.php#43"> Naidu,Aarush</a> </td><td>0</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td></tr>
<tr> <td>42</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 69 </span><span class="notitle male"> </span> <a href="playercard.php#69"> Menghani,Ishaan</a> </td><td>0</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td></tr>
<tr> <td>43</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 72 </span><span class="notitle male"> </span> <a href="playercard.php#72"> Pathiyassery,Emir</a> </td><td>0</td><td class="result">0    </td><td>0</td><td class="name">( not paired )</td><td></td></tr>
<tr> <td>44</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span class="idwhite"> 28 </span><span class="notitle male"> </span> <a href="playercard.php#28"> Dhar, Shubham</a> </td><td>0</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td></tr>
</tbody>
</table>
</DIV><hr>
		  </div>
		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p><a href="http://www.vegachess.com" target="_blank">Generated by Vega</a> All rights reserved</p><p>(Arbiter/Club : Hobsons Bay Chess Club - AUS)
  <?php if (file_exists($_SERVER['DOCUMENT_ROOT'].'/siteprivacy.php')) include($_SERVER['DOCUMENT_ROOT'].'/siteprivacy.php'); ?>    </div>  </div>  </div> </div> 
   </footer>
     </div>
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script></body>
</html>