<!DOCTYPE html>
<html lang="en"><head> 
<meta charset="UTF-8">
<meta name="description" content="chess tournament">
<meta name="author" content="www.vegachess.com">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
<title>2026 HBCC Hobsons Bay Juniors Rapid Championship</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="stylenew.css" type="text/css" >
    </head>
<body>
<div class="d-flex flex-column justify-content-between h-100">
 <nav class="navbar navbar-expand-lg fixed-top">
                <div class="container">    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0"><li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Info</a>
<ul class="dropdown-menu">
<li><a class="dropdown-item" href="schedule.php"> Schedule </a></li><li><a class="dropdown-item" href="tourstat.php">Statistics</a></li> </ul></li><li class="nav-item dropdown">   <a class="nav-link" href="index.php" >Players</a>
</li><li class="nav-item"><a class="nav-link " href="pairs5.php" >Pairings</a>
</li><li class="nav-item"><a class="nav-link" href="standings.php" >Standings</a>
</li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tables</a>
<ul class="dropdown-menu"><li><a class="dropdown-item" href="crosstable.php"> Cross table </a></li><li><a class="dropdown-item" href="crosstablescore.php"> Cross table and standings </a></li><li><a class="dropdown-item" href="rankinggroup.php"> Standings by Rtg groups </a></li><li><a class="dropdown-item" href="rankingagegroup.php"> Standings by age groups </a></li><li><a class="dropdown-item" href="rankcat.php"> Standings by title </a></li><li><a class="dropdown-item" href="rankTeams.php"> Rank Teams </a></li><li><a class="dropdown-item" href="summaryFederations.php"> Summary Federations </a></li><li><a class="dropdown-item" href="summaryOrigin.php"> Summary Origin </a></li></ul></li><li class="nav-item"><a class="nav-link" href="games.php" >Games</a>
</li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reports</a>
<ul class="dropdown-menu">          <li><a class="dropdown-item" href="felovar.php">FIDE Rating</a></li>          <li><a class="dropdown-item" href="fideplayercard.php">FIDE Player Card</a></li>           <li><a class="dropdown-item" href="nelovar.php">National rating</a></li>          <li><a class="dropdown-item" href="playercard.php">National Player Card</a></li></ul></li></ul> </div>
</div>
</nav>
 <section id="hero" class="d-flex align-items-center">
                <div class="container-fluid">
                    <div class="row items-center">
                        <div class="col-12">
                            <div class="flex flex-column justify-content-center text-center text-white">			<h1 class="mb-3" style="text-shadow: 2px 2px 4px #000000;" >2026 HBCC Hobsons Bay Juniors Rapid Championship</h1>		    <h5 class="mb-1">Hobsons Bay (AUS)</h5>		    <h5> 18/07/2026 - 18/07/2026</h5>   </div>
 </div> 
 </div>
 </div> 
 </section>
 <section id="main" class="pt-3 mb-auto">
                <div class="container-fluid">
                    <div class="row">
                        <div class="d-none d-lg-block col-1 ps-0">
                            <div class="d-flex flex-column w-full overflow-hidden"> </div> </div> <div class="col-12 col-lg-10">
  <div class="d-flex flex-column"> <div class="btn-toolbar mb-4 mt-4 d-flex align-items-center"> 
<h5>Pairing of round 4, at 12:00 of 18/07/2026</h5>
   	<div class="btn-group mx-5"> 
<?php include("pairing.php"); ?>
   	</div>
 </div>
<div class="table-responsive"><table class="table table-sm table-striped"> 
<thead><tr><th>Bo.</th><th>Fed</th><th>Origin</th><th>White Player</th><th>Pts</th><th>Result</th><th>Pts</th><th>Black Player</th><th>Origin</th><th>Fed</th></tr></thead><tbody>
<tr> <td>1</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 2 </span><span class="title male"> CM</span> <a href="playercard.php#2"> Lingineni,Khushal</a> </td><td>3</td><td class="result">1 - 0</td><td>3</td><td class="name"><span class="idblack">9 </span><span class="notitle male"> </span> <a href="playercard.php#9"> Batyrbekov, Kaisar</a></td><td></td><td><img class="shadow" src="flag/aus.png" alt="AUS"></td></tr>
<tr> <td>2</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 4 </span><span class="notitle male"> </span> <a href="playercard.php#4"> Parker,Lucas</a> </td><td>3</td><td class="result">1 - 0</td><td>3</td><td class="name"><span class="idblack">13 </span><span class="notitle male"> </span> <a href="playercard.php#13"> Annapureddy,Dhruthin Reddy</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>3</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 12 </span><span class="notitle male"> </span> <a href="playercard.php#12"> Ramanathan,Ashwin</a> </td><td>3</td><td class="result">1 - 0</td><td>3</td><td class="name"><span class="idblack">5 </span><span class="notitle male"> </span> <a href="playercard.php#5"> Kansal,Nuwan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>4</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 6 </span><span class="title female"> WCM</span> <a href="playercard.php#6"> Katakam,Deethya Sai</a> </td><td>3</td><td class="result">1 - 0</td><td>3</td><td class="name"><span class="idblack">21 </span><span class="notitle male"> </span> <a href="playercard.php#21"> Munro,Lachlan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>5</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 24 </span><span class="notitle male"> </span> <a href="playercard.php#24"> Ruaya,Rohan</a> </td><td>3</td><td class="result">0 - 1</td><td>3</td><td class="name"><span class="idblack">7 </span><span class="notitle male"> </span> <a href="playercard.php#7"> Bodke,Krishna Manthan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>6</td><td><img class="shadow" src="flag/aus.png" alt="AUS"></td><td></td><td class="name"> <span class="idwhite"> 14 </span><span class="notitle male"> </span> <a href="playercard.php#14"> Batyrbekov, Aidan</a> </td><td>3</td><td class="result">0 - 1</td><td>2.5</td><td class="name"><span class="idblack">8 </span><span class="notitle male"> </span> <a href="playercard.php#8"> Mai Nhuan Phat</a></td><td></td><td><img class="shadow" src="flag/os.png" alt="OS"></td></tr>
<tr> <td>7</td><td><img class="shadow" src="flag/os.png" alt="OS"></td><td></td><td class="name"> <span class="idwhite"> 28 </span><span class="notitle male"> </span> <a href="playercard.php#28"> Ahmad,Ihtiram</a> </td><td>2.5</td><td class="result">0 - 1</td><td>2.5</td><td class="name"><span class="idblack">11 </span><span class="notitle male"> </span> <a href="playercard.php#11"> Rathore,Akshobhya</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>8</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 22 </span><span class="notitle male"> </span> <a href="playercard.php#22"> Huang,Michael</a> </td><td>2.5</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">1 </span><span class="title male"> FM</span> <a href="playercard.php#1"> Annapureddy,Rheyansh Reddy</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>9</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 10 </span><span class="notitle male"> </span> <a href="playercard.php#10"> Ha, Aeson</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">48 </span><span class="notitle male"> </span> <a href="playercard.php#48"> Yong,Leonard</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>10</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 36 </span><span class="notitle male"> </span> <a href="playercard.php#36"> Gali,Joyel Evan</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">15 </span><span class="notitle male"> </span> <a href="playercard.php#15"> Rawat,Vivaan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>11</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 16 </span><span class="notitle male"> </span> <a href="playercard.php#16"> Jyothi Nikhil,Neev</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">50 </span><span class="notitle female"> </span> <a href="playercard.php#50"> Fang,Candice</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>12</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 41 </span><span class="notitle male"> </span> <a href="playercard.php#41"> Moser,William</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">17 </span><span class="notitle male"> </span> <a href="playercard.php#17"> Annadasu,Shreyansh</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>13</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 18 </span><span class="notitle male"> </span> <a href="playercard.php#18"> Ashok,Arjun</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">53 </span><span class="notitle female"> </span> <a href="playercard.php#53"> Kommina,Bhavishya</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>14</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 45 </span><span class="notitle male"> </span> <a href="playercard.php#45"> Singh,Sumair</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">19 </span><span class="notitle male"> </span> <a href="playercard.php#19"> Balaji,Sai Sivesh</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>15</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 20 </span><span class="notitle male"> </span> <a href="playercard.php#20"> Bhat,Dhruv</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">69 </span><span class="notitle female"> </span> <a href="playercard.php#69"> Madduluri,Advaitha</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>16</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 49 </span><span class="notitle male"> </span> <a href="playercard.php#49"> Krishnan,Sanjit</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">23 </span><span class="notitle male"> </span> <a href="playercard.php#23"> Le,Khoi Nguyen</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>17</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 26 </span><span class="notitle male"> </span> <a href="playercard.php#26"> Shaiek,Nihal</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">84 </span><span class="notitle male"> </span> <a href="playercard.php#84"> Li,Douglas</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>18</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 51 </span><span class="notitle male"> </span> <a href="playercard.php#51"> Bhadrapura, Vismay</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">27 </span><span class="notitle male"> </span> <a href="playercard.php#27"> Saha,Avinandan (Arjun)</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>19</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 54 </span><span class="notitle male"> </span> <a href="playercard.php#54"> Saha,Arya</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">29 </span><span class="notitle female"> </span> <a href="playercard.php#29"> Prince,Aliza</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>20</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 30 </span><span class="notitle male"> </span> <a href="playercard.php#30"> Vemula,Thamoghna</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">86 </span><span class="notitle male"> </span> <a href="playercard.php#86"> Malik,Eklavya</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>21</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 56 </span><span class="notitle male"> </span> <a href="playercard.php#56"> Wang, Evan</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">31 </span><span class="notitle male"> </span> <a href="playercard.php#31"> Watson,Jacob</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>22</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 34 </span><span class="notitle male"> </span> <a href="playercard.php#34"> Ni,Brandon</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">102 </span><span class="notitle male"> </span> <a href="playercard.php#102"> Zhuang,Raymond</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>23</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 68 </span><span class="notitle male"> </span> <a href="playercard.php#68"> Veeragandham,Gowtham</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">35 </span><span class="notitle male"> </span> <a href="playercard.php#35"> Tadakamadla,Ahaan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>24</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 70 </span><span class="notitle female"> </span> <a href="playercard.php#70"> Goh,Daphne</a> </td><td>2</td><td class="result">0 - 1</td><td>1.5</td><td class="name"><span class="idblack">33 </span><span class="notitle male"> </span> <a href="playercard.php#33"> Nema,Nivaan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>25</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 46 </span><span class="notitle male"> </span> <a href="playercard.php#46"> Krishnan,Sanjay</a> </td><td>1.5</td><td class="result">0 - 1</td><td>1.5</td><td class="name"><span class="idblack">3 </span><span class="title male"> CM</span> <a href="playercard.php#3"> Nguyen, Anh Kiet</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>26</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 91 </span><span class="notitle male"> </span> <a href="playercard.php#91"> Paul,Vivaan</a> </td><td>1.5</td><td class="result">1 - 0</td><td>1.5</td><td class="name"><span class="idblack">37 </span><span class="notitle female"> </span> <a href="playercard.php#37"> Venkat,Nyra</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>27</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 39 </span><span class="notitle female"> </span> <a href="playercard.php#39"> Kaur, Mishleen</a> </td><td>1.5</td><td class="result">½ - ½</td><td>1.5</td><td class="name"><span class="idblack">73 </span><span class="notitle male"> </span> <a href="playercard.php#73"> Aquino, Zedric</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>28</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 71 </span><span class="notitle male"> </span> <a href="playercard.php#71"> Goh,Julian</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">25 </span><span class="notitle female"> </span> <a href="playercard.php#25"> Katakam,Aadhya Sai</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>29</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 38 </span><span class="notitle male"> </span> <a href="playercard.php#38"> Padoli,Darsh</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">75 </span><span class="notitle male"> </span> <a href="playercard.php#75"> Bacon,Levi</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>30</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 72 </span><span class="notitle male"> </span> <a href="playercard.php#72"> Akula,Ayaansh Ved</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">40 </span><span class="notitle male"> </span> <a href="playercard.php#40"> Rao,Krishay</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>31</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 76 </span><span class="notitle female"> </span> <a href="playercard.php#76"> Balaji,Poshya</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">42 </span><span class="notitle male"> </span> <a href="playercard.php#42"> You,Henry</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>32</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 77 </span><span class="notitle male"> </span> <a href="playercard.php#77"> Borle,Anvay</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">44 </span><span class="notitle male"> </span> <a href="playercard.php#44"> Goh,Nicholas</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>33</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 47 </span><span class="notitle male"> </span> <a href="playercard.php#47"> Tan,Lucas</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">79 </span><span class="notitle female"> </span> <a href="playercard.php#79"> Ding,Charlene</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>34</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 80 </span><span class="notitle male"> </span> <a href="playercard.php#80"> Hii,Elliott</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">55 </span><span class="notitle male"> </span> <a href="playercard.php#55"> Tsen,Jacob</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>35</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 85 </span><span class="notitle male"> </span> <a href="playercard.php#85"> Malik,Arjun</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">57 </span><span class="notitle male"> </span> <a href="playercard.php#57"> Rajan,Viaan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>36</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 58 </span><span class="notitle male"> </span> <a href="playercard.php#58"> Moser,Luke</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">88 </span><span class="notitle female"> </span> <a href="playercard.php#88"> Pai,Tesha</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>37</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 60 </span><span class="notitle male"> </span> <a href="playercard.php#60"> Spriggs,Harvey</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">90 </span><span class="notitle male"> </span> <a href="playercard.php#90"> Panchaparvala,Sriram</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>38</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 93 </span><span class="notitle male"> </span> <a href="playercard.php#93"> Sethi,Vivaan</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">61 </span><span class="notitle male"> </span> <a href="playercard.php#61"> Balamurugan,Soorya</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>39</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 62 </span><span class="notitle male"> </span> <a href="playercard.php#62"> Menghani,Ishaan</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">94 </span><span class="notitle male"> </span> <a href="playercard.php#94"> Srinivasan,Sathvik</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>40</td><td><img class="shadow" src="flag/aus.png" alt="AUS"></td><td></td><td class="name"> <span class="idwhite"> 95 </span><span class="notitle male"> </span> <a href="playercard.php#95"> Sun,Aaron</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">63 </span><span class="notitle male"> </span> <a href="playercard.php#63"> Pradeep,Mayukh</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>41</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 64 </span><span class="notitle male"> </span> <a href="playercard.php#64"> Bodke,Aryan</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">96 </span><span class="notitle female"> </span> <a href="playercard.php#96"> Thambavitage,Pahansa</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>42</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 99 </span><span class="notitle female"> </span> <a href="playercard.php#99"> Yang,Heesan</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">65 </span><span class="notitle male"> </span> <a href="playercard.php#65"> Bala,Neil</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>43</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 66 </span><span class="notitle male"> </span> <a href="playercard.php#66"> Jyothi Nikhil,Vihaan</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">98 </span><span class="notitle male"> </span> <a href="playercard.php#98"> Vithanage,Binon</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>44</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 100 </span><span class="notitle male"> </span> <a href="playercard.php#100"> Yee,Julian</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">67 </span><span class="notitle male"> </span> <a href="playercard.php#67"> Bala,Jake</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>45</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 43 </span><span class="notitle male"> </span> <a href="playercard.php#43"> Samraat,Aayush</a> </td><td>0.5</td><td class="result">0 - 1</td><td>0.5</td><td class="name"><span class="idblack">89 </span><span class="notitle male"> </span> <a href="playercard.php#89"> Panchaparvala,Rohan Aditya</a></td><td></td><td><img class="shadow" src="flag/vic`.png" alt="VIC`"></td></tr>
<tr> <td>46</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 52 </span><span class="notitle male"> </span> <a href="playercard.php#52"> Pentela, Tharun</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">82 </span><span class="notitle female"> </span> <a href="playercard.php#82"> Kommina, Nihira</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>47</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 87 </span><span class="notitle male"> </span> <a href="playercard.php#87"> Mathew,Jake</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">59 </span><span class="notitle male"> </span> <a href="playercard.php#59"> Barar,Ridam</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>48</td><td><img class="shadow" src="flag/os.png" alt="OS"></td><td></td><td class="name"> <span class="idwhite"> 74 </span><span class="notitle male"> </span> <a href="playercard.php#74"> Athukorala,Senula Ekmitha</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">83 </span><span class="notitle male"> </span> <a href="playercard.php#83"> Koppuravuri,Haneesh</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>49</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 78 </span><span class="notitle male"> </span> <a href="playercard.php#78"> Borle,Swarit</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">92 </span><span class="notitle male"> </span> <a href="playercard.php#92"> Salimeda,Yuvan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>50</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 97 </span><span class="notitle male"> </span> <a href="playercard.php#97"> Trinh,Joseph</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">81 </span><span class="notitle male"> </span> <a href="playercard.php#81"> Kirieldeniya Don, George</a></td><td></td><td><img class="shadow" src="flag/os.png" alt="OS"></td></tr>
<tr> <td>51</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 101 </span><span class="notitle female"> </span> <a href="playercard.php#101"> Yong,Mabel</a> </td><td>0</td><td class="result">1    </td><td>0</td><td class="name">( bye )</td><td></td><td></td></tr>
<tr> <td>52</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 32 </span><span class="notitle male"> </span> <a href="playercard.php#32"> Li,Donghan</a> </td><td>0</td><td class="result">0    </td><td>0</td><td class="name">( not paired )</td><td></td><td></td></tr>
</tbody>
</table>
</DIV><hr>
		  </div>
		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p><a href="http://www.vegachess.com" target="_blank">Generated by Vega</a> All rights reserved</p><p>(Arbiter/Club : Hobsons Bay Chess Club - AUS)
  <?php if (file_exists($_SERVER['DOCUMENT_ROOT'].'/siteprivacy.php')) include($_SERVER['DOCUMENT_ROOT'].'/siteprivacy.php'); ?>    </div>  </div>  </div> </div> 
   </footer>
     </div>
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script></body>
</html>