<?php include "navbar.php"; ?>
<div class="d-flex flex-column">
<h4>National rating variation at round 5</h4>
 <div class="table-responsive"> <table class="table table-striped "><thead><tr><th>N</th><th>T</th><th>Name</th><th>Nat ID</th><th>Rtg</th><th>Ng</th><th>ARO</th><th>Var</tr></thead><tbody></tbody></table></div></div>		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p> <a class="text-primary" href="http://www.vegachess.com" target="_blank">Generated by Orion</a> All rights reserved </p><p class="text-body-secondary">(Arbiter/Club : Hobsons Bay Chess Club - AUS )</p>
    </div>  </div>  </div> </div> 
  <?php include("../adsensehor.php"); ?> 
   </footer>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>  <?php include "../google.php"; ?>
</body>
</html>