<?php include "navbar.php"; ?>
<div class="d-flex flex-column">
<h2 class="mb-4">Player Statistics</h2> <div class="table-responsive"> <table class="table table-striped"> 
<thead><tr><th>Type</th><th>N</th><th>Federations</th><th>from host Fed.</th><th>From other Fed.</th></tr></thead><tbody><tr><td><b>Rated</b></td><td>47</td><td>5</td><td>35</td><td>12</td></tr><tr><td><b>Unrated</b></td><td>14</td><td>3</td><td>6</td><td>8</td></tr><tr><td><b> GM </b></td><td>0</td><td>0</td><td>0</td><td>0</td></tr><tr><td><b> WGM </b></td><td>0</td><td>0</td><td>0</td><td>0</td></tr><tr><td><b> IM </b></td><td>0</td><td>0</td><td>0</td><td>0</td></tr><tr><td><b> WIM </b></td><td>0</td><td>0</td><td>0</td><td>0</td></tr><tr><td><b> FM </b></td><td>2</td><td>1</td><td>2</td><td>0</td></tr><tr><td><b> WFM </b></td><td>0</td><td>0</td><td>0</td><td>0</td></tr></tbody></table></div></div>		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p> <a class="text-primary" href="http://www.vegachess.com" target="_blank">Generated by Orion</a> All rights reserved </p><p class="text-body-secondary">(Arbiter/Club : Hobsons Bay Chess Club - AUS )</p>
    </div>  </div>  </div> </div> 
   </footer>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script></body>
</html>