<!DOCTYPE html>
<html lang="en"><head> <meta charset="UTF-8">
<meta name="description" content="chess tournament">
<meta name="author" content="www.vegachess.com">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
<title>Honourable Bob Juniors 2024</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link rel="stylesheet" href="stylenew.css" type="text/css" >
    </head>
<body>
<div class="d-flex flex-column justify-content-between h-100"> <nav class="navbar navbar-expand-lg bg-light fixed-top">
                <div class="container">  <a class="navbar-brand d-flex align-items-center" href="#" style="width: 24px;"> <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M20,8h0L14,2.74a3,3,0,0,0-4,0L4,8a3,3,0,0,0-1,2.26V19a3,3,0,0,0,3,3H18a3,3,0,0,0,3-3V10.25A3,3,0,0,0,20,8ZM14,20H10V15a1,1,0,0,1,1-1h2a1,1,0,0,1,1,1Zm5-1a1,1,0,0,1-1,1H16V15a3,3,0,0,0-3-3H11a3,3,0,0,0-3,3v5H6a1,1,0,0,1-1-1V10.25a1,1,0,0,1,.34-.75l6-5.25a1,1,0,0,1,1.32,0l6,5.25a1,1,0,0,1,.34.75Z" fill="#000"/></svg>
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0"><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Info</a>
<ul class="dropdown-menu"><li><a class="dropdown-item" href="schedule.php"> Schedule </a></li><li><a class="dropdown-item" href="tourstat.php">Statistics</a></li> </ul></li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Players</a>
<ul class="dropdown-menu"><li><a class="dropdown-item" href="index.php">Sorted by Rating</a></li><li><a class="dropdown-item" href="playersname.php">Sorted by Name</a></li></ul></li><li class="nav-item"><a class="nav-link " href="pairs5.php" >Pairings</a>
</li><li class="nav-item"><a class="nav-link" href="standings.php" >Standings</a>
</li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tables</a>
<ul class="dropdown-menu"><li><a class="dropdown-item" href="schedule.php"> Schedule </a></li><li><a class="dropdown-item" href="crosstablescore.php"> Cross table by score </a></li><li><a class="dropdown-item" href="rankinggroup.php"> Standings by Rtg groups </a></li><li><a class="dropdown-item" href="rankingagegroup.php"> Standings by age groups </a></li><li><a class="dropdown-item" href="rankcat.php"> Standings by title </a></li><li><a class="dropdown-item" href="rankTeams.php"> Rank Teams </a></li><li><a class="dropdown-item" href="summaryFederations.php"> Summary Federations </a></li><li><a class="dropdown-item" href="summaryOrigin.php"> Summary Origin </a></li></ul></li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reports</a>
<ul class="dropdown-menu">          <li><a class="dropdown-item" href="felovar.php">FIDE Rating</a></li>          <li><a class="dropdown-item" href="fideplayercard.php">FIDE Player Card</a></li>           <li><a class="dropdown-item" href="nelovar.php">National rating</a></li>          <li><a class="dropdown-item" href="playercard.php">National Player Card</a></li></ul></li></ul> </div>
</div>
</nav>
 <section id="main" class="pt-5 mb-auto">
                <div class="container-fluid">
                    <div class="row">
                        <div class="d-none d-lg-block col-1 ps-0">
                            <div class="d-flex flex-column w-full overflow-hidden"> </div> </div> <div class="col-12 col-lg-10">
  <div class="d-flex flex-column">   <h3 class="mb-4 mt-4">Pairings</h3> <div class="btn-toolbar"> 
   	<div class="btn-group"> <script type="text/javascript" src="pairing.js"></script>
   	</div>
 </div>
<h5 class="mb-2 mt-2">Pairing of round 1</h5>
<div class="table-responsive"><table class="table table-sm table-striped"> 
<thead><tr><th>Bo.</th><th>Fed</th><th>White Player</th><th>Pts</th><th>Result</th><th>Pts</th><th>Black Player</th><th>Fed</th></tr></thead><tbody>
<tr> <td>1</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;18 </span> <a href="playercard.php#18"> Ashok,Arjun</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0 - 1</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;&nbsp;1 </span> <a href="playercard.php#1"> Wei,Andrew</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>2</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;&nbsp;2 </span> <a href="playercard.php#2"> Majety,Rohan</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">1 - 0</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;19 </span> <a href="playercard.php#19"> Babu,Dilesh</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>3</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;20 </span> <a href="playercard.php#20"> Bo,Jamie</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0 - 1</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;&nbsp;3 </span> <a href="playercard.php#3"> Nguyen,Anh Kiet</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>4</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;&nbsp;4 </span> <a href="playercard.php#4"> Parker,Lucas</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">1 - 0</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;21 </span> <a href="playercard.php#21"> Bruno,Iris</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>5</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;22 </span> <a href="playercard.php#22"> Husain,Lamiah</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0 - 1</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;&nbsp;5 </span> <a href="playercard.php#5"> Morris,Elijah</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>6</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;&nbsp;6 </span> <a href="playercard.php#6"> Tavassoli,Seyedeh Tara</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0 - 1</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;23 </span> <a href="playercard.php#23"> Jackson,Liam</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>7</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;24 </span> <a href="playercard.php#24"> Kukdeja,Aarav</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0 - 1</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;&nbsp;7 </span> <a href="playercard.php#7"> Nguyen,Tuan Kiet</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>8</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;&nbsp;8 </span> <a href="playercard.php#8"> Huang,Michael</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">1 - 0</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;25 </span> <a href="playercard.php#25"> Kukdeja,Reva</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>9</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;26 </span> <a href="playercard.php#26"> Marchant,Ben</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0 - 1</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;&nbsp;9 </span> <a href="playercard.php#9"> Bo,Jeremie</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>10</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;10 </span> <a href="playercard.php#10"> Marasinghe,Claire</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">1 - 0</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;27 </span> <a href="playercard.php#27"> Muddu,Tejas</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>11</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;28 </span> <a href="playercard.php#28"> Naidu,Aarush</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0 - 1</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;11 </span> <a href="playercard.php#11"> Ruaya,Rohan</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>12</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;12 </span> <a href="playercard.php#12"> Batyrbekov,Kaisar</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">1 - 0</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;29 </span> <a href="playercard.php#29"> Nethi,Karthika</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>13</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;30 </span> <a href="playercard.php#30"> Pathiyassery,Emir</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">1 - 0</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;13 </span> <a href="playercard.php#13"> Goh,Nicholas</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>14</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;14 </span> <a href="playercard.php#14"> Batyrbekov,Aidan</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">1 - 0</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;31 </span> <a href="playercard.php#31"> Rathnayaka,Suwanma Dulasni</a></td><td><img class="shadow" src="flag/aus.png" alt="AUS"></td></tr>
<tr> <td>15</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;32 </span> <a href="playercard.php#32"> Senan Rathnayaka,Ranithu</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">1 - 0</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;15 </span> <a href="playercard.php#15"> Chan,Abby</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>16</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;16 </span> <a href="playercard.php#16"> Guggilla,Krithvik</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">1 - 0</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;33 </span> <a href="playercard.php#33"> Shenbaga,Kabilan</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>17</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;34 </span> <a href="playercard.php#34"> Vassallo,Romeo</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0 - 1</td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name"><span style="font-family: courier;" class="badge text-bg-primary">&nbsp;17 </span> <a href="playercard.php#17"> Amutha Raja,Nalan</a></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>18</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;35 </span> <a href="playercard.php#35"> Venkatesh,Arvind</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">1    </td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name">( bye )</td><td></td></tr>
<tr> <td>19</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;36 </span> <a href="playercard.php#36"> Vijayakumar,Rithvik</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0    </td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name">( not paired )</td><td></td></tr>
<tr> <td>20</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;37 </span> <a href="playercard.php#37"> Rai,Ishaan</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0    </td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name">( not paired )</td><td></td></tr>
<tr> <td>21</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td class="name"> <span style="font-family: courier;" class="badge text-bg-primary"> &nbsp;38 </span> <a href="playercard.php#38"> Yang,Yifan</a> </td><td> <span class="badge text-bg-secondary" > 0 </span></td><td class="result">0    </td><td> <span class="badge text-bg-secondary"> 0 </span></td><td class="name">( not paired )</td><td></td></tr>
</tbody>
</table>
</DIV><hr>
		  </div>
		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p><a href="http://www.vegachess.com" target="_blank">Generated by Vega</a> All rights reserved</p><p>(Arbiter/Club : Hobsons Bay Chess Club - AUS)
    </div>  </div>  </div> </div> 
   </footer>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script></body>
</html>