<!DOCTYPE html>
<html lang="en"><head> 
<meta charset="UTF-8">
<meta name="description" content="chess tournament">
<meta name="author" content="www.vegachess.com">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
<title>2026 HBCC Best in the West</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="stylenew.css" type="text/css" >
    </head>
<body>
<div class="d-flex flex-column justify-content-between h-100">
 <nav class="navbar navbar-expand-lg fixed-top">
                <div class="container">    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0"><li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Info</a>
<ul class="dropdown-menu">
<li><a class="dropdown-item" href="schedule.php"> Schedule </a></li><li><a class="dropdown-item" href="tourstat.php">Statistics</a></li> </ul></li><li class="nav-item dropdown">   <a class="nav-link" href="index.php" >Players</a>
</li><li class="nav-item"><a class="nav-link " href="pairs5.php" >Pairings</a>
</li><li class="nav-item"><a class="nav-link" href="standings.php" >Standings</a>
</li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tables</a>
<ul class="dropdown-menu"><li><a class="dropdown-item" href="crosstable.php"> Cross table </a></li><li><a class="dropdown-item" href="crosstablescore.php"> Cross table and standings </a></li><li><a class="dropdown-item" href="rankinggroup.php"> Standings by Rtg groups </a></li><li><a class="dropdown-item" href="rankingagegroup.php"> Standings by age groups </a></li><li><a class="dropdown-item" href="rankcat.php"> Standings by title </a></li><li><a class="dropdown-item" href="rankTeams.php"> Rank Teams </a></li><li><a class="dropdown-item" href="summaryFederations.php"> Summary Federations </a></li><li><a class="dropdown-item" href="summaryOrigin.php"> Summary Origin </a></li></ul></li><li class="nav-item"><a class="nav-link" href="games.php" >Games</a>
</li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reports</a>
<ul class="dropdown-menu">          <li><a class="dropdown-item" href="felovar.php">FIDE Rating</a></li>          <li><a class="dropdown-item" href="fideplayercard.php">FIDE Player Card</a></li>           <li><a class="dropdown-item" href="nelovar.php">National rating</a></li>          <li><a class="dropdown-item" href="playercard.php">National Player Card</a></li></ul></li></ul> </div>
</div>
</nav>
 <section id="main" class="pt-3 mb-auto">
                <div class="container-fluid">
                    <div class="row">
                        <div class="d-none d-lg-block col-1 ps-0">
                            <div class="d-flex flex-column w-full overflow-hidden"> </div> </div> <div class="col-12 col-lg-10">
  <div class="d-flex flex-column"> <div class="btn-toolbar mb-4 mt-4 d-flex align-items-center"> 
<h5>Pairing of round 2 (accelerated), at 14:00 of 29/08/2026</h5>
   	<div class="btn-group mx-5"> 
<?php include("pairing.php"); ?>
   	</div>
 </div>
<div class="table-responsive"><table class="table table-sm table-striped"> 
<thead><tr><th>Bo.</th><th>Fed</th><th>Origin</th><th>White Player</th><th>Pts</th><th>Result</th><th>Pts</th><th>Black Player</th><th>Origin</th><th>Fed</th></tr></thead><tbody>
<tr> <td>1</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 24 </span><span class="notitle male"> </span> <a href="playercard.php#24"> Dakic,Dusan</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">1 </span><span class="title male"> IM</span> <a href="playercard.php#1"> Hernandez Sanchez, Jairo Andres</a></td><td></td><td><img class="shadow" src="flag/col.png" alt="COL"></td></tr>
<tr> <td>2</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 2 </span><span class="title male"> FM</span> <a href="playercard.php#2"> Soo,Kai Jie</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">25 </span><span class="notitle male"> </span> <a href="playercard.php#25"> Bodke,Krishna Manthan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>3</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 26 </span><span class="notitle male"> </span> <a href="playercard.php#26"> Bhadrapura,Vismay</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">3 </span><span class="title male"> FM</span> <a href="playercard.php#3"> Nemeth,John</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>4</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 4 </span><span class="title male"> FM</span> <a href="playercard.php#4"> Dragicevic,Domagoj</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">27 </span><span class="notitle male"> </span> <a href="playercard.php#27"> Saha,Arya</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>5</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 29 </span><span class="title female"> WCM</span> <a href="playercard.php#29"> Katakam,Deethya Sai</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">5 </span><span class="title male"> FM</span> <a href="playercard.php#5"> Annapureddy,Rheyansh Reddy</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>6</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 30 </span><span class="notitle female"> </span> <a href="playercard.php#30"> Davis,Sophie</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">7 </span><span class="title male"> FM</span> <a href="playercard.php#7"> Bassig,Hamish</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>7</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 8 </span><span class="title male"> CM</span> <a href="playercard.php#8"> Smith,Declan</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">31 </span><span class="notitle male"> </span> <a href="playercard.php#31"> Whitford,Matthew</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>8</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 32 </span><span class="title female"> WIM</span> <a href="playercard.php#32"> Szuveges,Narelle S</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">9 </span><span class="notitle male"> </span> <a href="playercard.php#9"> Poberezovsky, Daniel</a></td><td></td><td><img class="shadow" src="flag/aus.png" alt="AUS"></td></tr>
<tr> <td>9</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 11 </span><span class="notitle male"> </span> <a href="playercard.php#11"> Zheng,Ryan</a> </td><td>1</td><td class="result">½ - ½</td><td>1</td><td class="name"><span class="idblack">33 </span><span class="notitle male"> </span> <a href="playercard.php#33"> Tai,Ethan</a></td><td></td><td><img class="shadow" src="flag/os.png" alt="OS"></td></tr>
<tr> <td>10</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 34 </span><span class="notitle male"> </span> <a href="playercard.php#34"> Ramanathan,Ashwin</a> </td><td>1</td><td class="result">½ - ½</td><td>1</td><td class="name"><span class="idblack">12 </span><span class="notitle male"> </span> <a href="playercard.php#12"> Krishnan,Anirudh</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>11</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 58 </span><span class="notitle male"> </span> <a href="playercard.php#58"> Batyrbekov,Aidan</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">14 </span><span class="notitle male"> </span> <a href="playercard.php#14"> Lacson,Joemar</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>12</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 15 </span><span class="notitle male"> </span> <a href="playercard.php#15"> Hogg,Dean</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">44 </span><span class="notitle male"> </span> <a href="playercard.php#44"> Rathore,Akshobhya</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>13</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 60 </span><span class="notitle male"> </span> <a href="playercard.php#60"> Rawat,Vivaan</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">16 </span><span class="notitle male"> </span> <a href="playercard.php#16"> Smith,Jack</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>14</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 17 </span><span class="notitle male"> </span> <a href="playercard.php#17"> Pitono,Abraham</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">50 </span><span class="notitle male"> </span> <a href="playercard.php#50"> Batyrbekov,Kaisar</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>15</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 72 </span><span class="notitle male"> </span> <a href="playercard.php#72"> Sheth,Adidev</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">18 </span><span class="notitle male"> </span> <a href="playercard.php#18"> Pentela,Suman</a></td><td></td><td><img class="shadow" src="flag/ind.png" alt="IND"></td></tr>
<tr> <td>16</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 19 </span><span class="title male"> CM</span> <a href="playercard.php#19"> Davis,Tony J</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">65 </span><span class="notitle female"> </span> <a href="playercard.php#65"> Katakam,Aadhya Sai</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>17</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 21 </span><span class="notitle male"> </span> <a href="playercard.php#21"> Hari,Dhruv</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">73 </span><span class="notitle male"> </span> <a href="playercard.php#73"> Tempany,Ayden</a></td><td></td><td><img class="shadow" src="flag/wa.png" alt="WA"></td></tr>
<tr> <td>18</td><td><img class="shadow" src="flag/tas.png" alt="TAS"></td><td></td><td class="name"> <span class="idwhite"> 35 </span><span class="notitle male"> </span> <a href="playercard.php#35"> Djatschenko,Addison</a> </td><td>0.5</td><td class="result">0 - 1</td><td>0.5</td><td class="name"><span class="idblack">10 </span><span class="title male"> CM</span> <a href="playercard.php#10"> Nguyen,Anh Kiet</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>19</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 6 </span><span class="title male"> FM</span> <a href="playercard.php#6"> Li,Jackie</a> </td><td>0</td><td class="result">1 - 0</td><td>0.5</td><td class="name"><span class="idblack">37 </span><span class="notitle male"> </span> <a href="playercard.php#37"> Menezes,Eric</a></td><td></td><td><img class="shadow" src="flag/sa.png" alt="SA"></td></tr>
<tr> <td>20</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 13 </span><span class="notitle male"> </span> <a href="playercard.php#13"> Wang,Tim</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">71 </span><span class="notitle male"> </span> <a href="playercard.php#71"> Laffey,Julian</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>21</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 75 </span><span class="notitle male"> </span> <a href="playercard.php#75"> Kildea,James</a> </td><td>1</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">20 </span><span class="notitle male"> </span> <a href="playercard.php#20"> Kansal,Nuwan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>22</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 78 </span><span class="notitle female"> </span> <a href="playercard.php#78"> Yates,Anna</a> </td><td>1</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">23 </span><span class="notitle male"> </span> <a href="playercard.php#23"> Young,Matthew</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>23</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 28 </span><span class="notitle male"> </span> <a href="playercard.php#28"> Rodriguez,Maickel</a> </td><td>0</td><td class="result">½ - ½</td><td>1</td><td class="name"><span class="idblack">76 </span><span class="notitle male"> </span> <a href="playercard.php#76"> Wei,Andrew</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>24</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 82 </span><span class="notitle male"> </span> <a href="playercard.php#82"> Jagannathan,Shashvath</a> </td><td>1</td><td class="result">½ - ½</td><td>0</td><td class="name"><span class="idblack">36 </span><span class="notitle male"> </span> <a href="playercard.php#36"> Rao, Krishay</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>25</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 38 </span><span class="notitle male"> </span> <a href="playercard.php#38"> Wang,Evan</a> </td><td>0</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">79 </span><span class="notitle female"> </span> <a href="playercard.php#79"> Bo,Jamie</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>26</td><td><img class="shadow" src="flag/qld.png" alt="QLD"></td><td></td><td class="name"> <span class="idwhite"> 39 </span><span class="notitle male"> </span> <a href="playercard.php#39"> Kodituwakku,Damhiru</a> </td><td>0</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">81 </span><span class="notitle male"> </span> <a href="playercard.php#81"> Li,Harry</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>27</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 84 </span><span class="notitle male"> </span> <a href="playercard.php#84"> Vemula,Thamoghna</a> </td><td>1</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">40 </span><span class="notitle male"> </span> <a href="playercard.php#40"> Chatha, Harmandeep</a></td><td></td><td><img class="shadow" src="flag/aus.png" alt="AUS"></td></tr>
<tr> <td>28</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 41 </span><span class="notitle male"> </span> <a href="playercard.php#41"> Milic,James</a> </td><td>0</td><td class="result">½ - ½</td><td>1</td><td class="name"><span class="idblack">85 </span><span class="notitle male"> </span> <a href="playercard.php#85"> Hu,Timothy Tianmeng</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>29</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 86 </span><span class="notitle male"> </span> <a href="playercard.php#86"> Saha,Avinandan (Arjun)</a> </td><td>1</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">42 </span><span class="notitle male"> </span> <a href="playercard.php#42"> Bambridge,Greg</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>30</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 43 </span><span class="notitle male"> </span> <a href="playercard.php#43"> Parker,Lucas</a> </td><td>0</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">87 </span><span class="notitle male"> </span> <a href="playercard.php#87"> Watson,Jacob</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>31</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 45 </span><span class="notitle male"> </span> <a href="playercard.php#45"> Humphreys,Scott</a> </td><td>0</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">89 </span><span class="notitle male"> </span> <a href="playercard.php#89"> Bo,Jeremie</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>32</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 88 </span><span class="notitle male"> </span> <a href="playercard.php#88"> Manoj,Dev</a> </td><td>1</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">46 </span><span class="notitle male"> </span> <a href="playercard.php#46"> Hogan,Steven</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>33</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 47 </span><span class="notitle male"> </span> <a href="playercard.php#47"> Paul,Nikash</a> </td><td>0</td><td class="result">½ - ½</td><td>1</td><td class="name"><span class="idblack">91 </span><span class="notitle female"> </span> <a href="playercard.php#91"> Venkat,Nyra</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>34</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 90 </span><span class="notitle male"> </span> <a href="playercard.php#90"> Shaiek,Nihal</a> </td><td>1</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">48 </span><span class="notitle male"> </span> <a href="playercard.php#48"> Ha,Aeson</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>35</td><td><img class="shadow" src="flag/aus.png" alt="AUS"></td><td></td><td class="name"> <span class="idwhite"> 49 </span><span class="notitle male"> </span> <a href="playercard.php#49"> Brockman, Roland</a> </td><td>0</td><td class="result">½ - ½</td><td>1</td><td class="name"><span class="idblack">94 </span><span class="notitle female"> </span> <a href="playercard.php#94"> Shah,Swaraa</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>36</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 51 </span><span class="notitle female"> </span> <a href="playercard.php#51"> Scenna,Luna</a> </td><td>0</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">98 </span><span class="notitle male"> </span> <a href="playercard.php#98"> Singh,Sumair</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>37</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 93 </span><span class="notitle male"> </span> <a href="playercard.php#93"> Goh,Nicholas</a> </td><td>1</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">52 </span><span class="notitle male"> </span> <a href="playercard.php#52"> Le Nguyen,Khoi</a></td><td></td><td><img class="shadow" src="flag/os.png" alt="OS"></td></tr>
<tr> <td>38</td><td><img class="shadow" src="flag/os.png" alt="OS"></td><td></td><td class="name"> <span class="idwhite"> 53 </span><span class="notitle female"> </span> <a href="playercard.php#53"> Siva,Mrinalini</a> </td><td>0</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">100 </span><span class="notitle male"> </span> <a href="playercard.php#100"> Subhash,Ryan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>39</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 95 </span><span class="notitle male"> </span> <a href="playercard.php#95"> Moser,William</a> </td><td>1</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">55 </span><span class="notitle female"> </span> <a href="playercard.php#55"> Guha,Shanaya</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>40</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 56 </span><span class="notitle male"> </span> <a href="playercard.php#56"> Wilkinson,Greg</a> </td><td>0</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">102 </span><span class="notitle male"> </span> <a href="playercard.php#102"> Balamurugan,Soorya</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>41</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 97 </span><span class="notitle male"> </span> <a href="playercard.php#97"> Zhao,Oscar</a> </td><td>1</td><td class="result">½ - ½</td><td>0</td><td class="name"><span class="idblack">59 </span><span class="notitle male"> </span> <a href="playercard.php#59"> Qi,Jaden</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>42</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 99 </span><span class="notitle male"> </span> <a href="playercard.php#99"> Moser,Luke</a> </td><td>1</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">61 </span><span class="notitle male"> </span> <a href="playercard.php#61"> Yendru,Srikrishna</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>43</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 62 </span><span class="notitle male"> </span> <a href="playercard.php#62"> Zhou,Zenan</a> </td><td>0</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">104 </span><span class="notitle female"> </span> <a href="playercard.php#104"> Fang,Candice</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>44</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 105 </span><span class="notitle male"> </span> <a href="playercard.php#105"> Das,Ayush</a> </td><td>1</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">63 </span><span class="notitle male"> </span> <a href="playercard.php#63"> Balaji,Sai Sivesh</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>45</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 64 </span><span class="notitle male"> </span> <a href="playercard.php#64"> Bhat,Dhruv</a> </td><td>0</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">106 </span><span class="notitle female"> </span> <a href="playercard.php#106"> Hu,Lydia Tianhui</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>46</td><td><img class="shadow" src="flag/os.png" alt="OS"></td><td></td><td class="name"> <span class="idwhite"> 66 </span><span class="notitle male"> </span> <a href="playercard.php#66"> Ahmad,Ihtiram</a> </td><td>0</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">113 </span><span class="notitle male"> </span> <a href="playercard.php#113"> Goh,Julian</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>47</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 107 </span><span class="notitle male"> </span> <a href="playercard.php#107"> Ganesh Kumar,Mukunth</a> </td><td>1</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">67 </span><span class="notitle male"> </span> <a href="playercard.php#67"> Ngo,William</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>48</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 68 </span><span class="notitle male"> </span> <a href="playercard.php#68"> Wales,Sam</a> </td><td>0</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">134 </span><span class="notitle male"> </span> <a href="playercard.php#134"> Upadhyay,Viaan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>49</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 129 </span><span class="notitle male"> </span> <a href="playercard.php#129"> Sathish,Sukrrish</a> </td><td>1</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">69 </span><span class="notitle female"> </span> <a href="playercard.php#69"> Mondal,Jahnavi</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>50</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 70 </span><span class="notitle male"> </span> <a href="playercard.php#70"> Jyothi Nikhil,Neev</a> </td><td>0</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">136 </span><span class="notitle male"> </span> <a href="playercard.php#136"> Vinu,Vinayak</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>51</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 77 </span><span class="notitle male"> </span> <a href="playercard.php#77"> Arora,Daanish</a> </td><td>0.5</td><td class="result">1F-0F</td><td>0.5</td><td class="name"><span class="idblack">92 </span><span class="notitle female"> </span> <a href="playercard.php#92"> Prince,Aliza</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>52</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 128 </span><span class="notitle male"> </span> <a href="playercard.php#128"> Saravanakumar,Thaswin</a> </td><td>0.5</td><td class="result">0 - 1</td><td>0.5</td><td class="name"><span class="idblack">83 </span><span class="notitle male"> </span> <a href="playercard.php#83"> Nema,Nivaan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>53</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 116 </span><span class="notitle male"> </span> <a href="playercard.php#116"> Dolor,Raymond</a> </td><td>0.5</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">80 </span><span class="notitle male"> </span> <a href="playercard.php#80"> Scenna,George</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>54</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 122 </span><span class="notitle male"> </span> <a href="playercard.php#122"> Mantrala,Vishruth</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">96 </span><span class="notitle female"> </span> <a href="playercard.php#96"> Kaur,Mishleen</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>55</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 101 </span><span class="notitle female"> </span> <a href="playercard.php#101"> Kommina,Bhavishya</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">123 </span><span class="notitle male"> </span> <a href="playercard.php#123"> Mantrala,Yuvan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>56</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 103 </span><span class="notitle male"> </span> <a href="playercard.php#103"> Samraat,Aayush</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">124 </span><span class="notitle male"> </span> <a href="playercard.php#124"> Menghani,Ishaan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>57</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 108 </span><span class="notitle female"> </span> <a href="playercard.php#108"> Madduluri,Advaitha</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">125 </span><span class="notitle female"> </span> <a href="playercard.php#125"> Mondal,Tanisha</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>58</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 126 </span><span class="notitle male"> </span> <a href="playercard.php#126"> Panchaparvala,Rohan Aditya</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">109 </span><span class="notitle male"> </span> <a href="playercard.php#109"> Pradeep,Mayukh</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>59</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 110 </span><span class="notitle male"> </span> <a href="playercard.php#110"> Jyothi Nikhil,Vihaan</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">127 </span><span class="notitle male"> </span> <a href="playercard.php#127"> Rubiano,Carlos Daniel</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>60</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 133 </span><span class="notitle male"> </span> <a href="playercard.php#133"> Tripathi,Aarav</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">111 </span><span class="notitle male"> </span> <a href="playercard.php#111"> Denny,William</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>61</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 112 </span><span class="notitle female"> </span> <a href="playercard.php#112"> Goh,Daphne</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">130 </span><span class="notitle male"> </span> <a href="playercard.php#130"> Sethi,Vivaan</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>62</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 114 </span><span class="notitle male"> </span> <a href="playercard.php#114"> Bacon,Levi</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">132 </span><span class="notitle male"> </span> <a href="playercard.php#132"> Tran,Khoa Dinh</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>63</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 135 </span><span class="notitle male"> </span> <a href="playercard.php#135"> Vinu,Vaishnav</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">115 </span><span class="notitle male"> </span> <a href="playercard.php#115"> Dolor,Lucas</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>64</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 118 </span><span class="notitle female"> </span> <a href="playercard.php#118"> Haller,Annabelle</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">137 </span><span class="notitle male"> </span> <a href="playercard.php#137"> Wang,Liam</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>65</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 139 </span><span class="notitle male"> </span> <a href="playercard.php#139"> Yadav, Yuvan</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">119 </span><span class="notitle male"> </span> <a href="playercard.php#119"> Hu,Nathanael Tianen</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>66</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 120 </span><span class="notitle male"> </span> <a href="playercard.php#120"> Lake,Logan</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">140 </span><span class="notitle male"> </span> <a href="playercard.php#140"> Yoon, Nile</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>67</td><td><img class="shadow" src="flag/os.png" alt="OS"></td><td></td><td class="name"> <span class="idwhite"> 141 </span><span class="notitle female"> </span> <a href="playercard.php#141"> Zhang,Luxi</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">121 </span><span class="notitle male"> </span> <a href="playercard.php#121"> Lee,William San</a></td><td></td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td></tr>
<tr> <td>68</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 57 </span><span class="notitle male"> </span> <a href="playercard.php#57"> Annadasu,Shreyansh</a> </td><td>0</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>69</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 74 </span><span class="notitle male"> </span> <a href="playercard.php#74"> Ruaya,Rohan</a> </td><td>1</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>70</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 22 </span><span class="notitle female"> </span> <a href="playercard.php#22"> Dissanayake,Vidushi</a> </td><td>0.5</td><td class="result">0    </td><td>0</td><td class="name">( not paired )</td><td></td><td></td></tr>
<tr> <td>71</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 54 </span><span class="notitle male"> </span> <a href="playercard.php#54"> Dissanayake,Naveen</a> </td><td>0.5</td><td class="result">0    </td><td>0</td><td class="name">( not paired )</td><td></td><td></td></tr>
<tr> <td>72</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 117 </span><span class="notitle male"> </span> <a href="playercard.php#117"> Gowda,Likhil</a> </td><td>0</td><td class="result">0    </td><td>0</td><td class="name">( not paired )</td><td></td><td></td></tr>
<tr> <td>73</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 131 </span><span class="notitle female"> </span> <a href="playercard.php#131"> Sood,Sara</a> </td><td>0</td><td class="result">0    </td><td>0</td><td class="name">( not paired )</td><td></td><td></td></tr>
<tr> <td>74</td><td><img class="shadow" src="flag/vic.png" alt="VIC"></td><td></td><td class="name"> <span class="idwhite"> 138 </span><span class="notitle male"> </span> <a href="playercard.php#138"> Wright,Leeyn</a> </td><td>0</td><td class="result">0    </td><td>0</td><td class="name">( not paired )</td><td></td><td></td></tr>
</tbody>
</table>
</DIV><hr>
		  </div>
		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p><a href="http://www.vegachess.com" target="_blank">Generated by Vega</a> All rights reserved</p><p>(Arbiter/Club : Casey Goh - AUS)
  <?php if (file_exists($_SERVER['DOCUMENT_ROOT'].'/siteprivacy.php')) include($_SERVER['DOCUMENT_ROOT'].'/siteprivacy.php'); ?>    </div>  </div>  </div> </div> 
   </footer>
     </div>
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script></body>
</html>