<?php include "navbar.php"; ?>
<div class="d-flex flex-column">
<h2 class="mb-4">Cross Table at round 5</h2> <div class="table-responsive"> <table class="table table-striped table-condensed">
<thead><tr><th>Rk</th><th>Team</th><th colspan="2">Fed</th><th>Pts</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th></tr></thead><tr><td>1</td><td><span class="badge text-bg-secondary">1</span> ACTJCL</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td class="score">23</td><td class="hole"> </td><td> 2&nbsp;</td><td> 6&nbsp;</td><td> 5&nbsp;</td><td> 4&nbsp;</td><td> 6&nbsp;</td></tr><tr><td>2</td><td><span class="badge text-bg-secondary">3</span> HBCC A</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td class="score">21.5</td><td> 4&nbsp;</td><td class="hole"> </td><td> 3.5&nbsp;</td><td> 4.5&nbsp;</td><td> 6&nbsp;</td><td> 3.5&nbsp;</td></tr><tr><td>3</td><td><span class="badge text-bg-secondary">2</span> HBCC B</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td class="score">14.5</td><td> 0&nbsp;</td><td> 2.5&nbsp;</td><td class="hole"> </td><td> 4&nbsp;</td><td> 4&nbsp;</td><td> 4&nbsp;</td></tr><tr><td>4</td><td><span class="badge text-bg-secondary">6</span> JZMC</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td class="score">12.5</td><td> 1&nbsp;</td><td> 1.5&nbsp;</td><td> 2&nbsp;</td><td class="hole"> </td><td> 3.5&nbsp;</td><td> 4.5&nbsp;</td></tr><tr><td>5</td><td><span class="badge text-bg-secondary">5</span> GCC</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td class="score">10</td><td> 2&nbsp;</td><td> 0&nbsp;</td><td> 2&nbsp;</td><td> 2.5&nbsp;</td><td class="hole"> </td><td> 3.5&nbsp;</td></tr><tr><td>6</td><td><span class="badge text-bg-secondary">4</span> ISCC</td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td class="score">8.5</td><td> 0&nbsp;</td><td> 2.5&nbsp;</td><td> 2&nbsp;</td><td> 1.5&nbsp;</td><td> 2.5&nbsp;</td><td class="hole"> </td></tr></table></div></div>		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p> <a class="text-primary" href="http://www.vegachess.com" target="_blank">Generated by Orion</a> All rights reserved </p><p class="text-body-secondary">(Arbiter/Club : Hobsons Bay Chess Club - AUS )</p>
    </div>  </div>  </div> </div> 
  <?php include("../adsensehor.php"); ?> 
   </footer>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>  <?php include "../google.php"; ?>
</body>
</html>