<?php include "navbar.php"; ?>
<div class="d-flex flex-column">
<h2 class="mb-4">Team composition</h2><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">1</span> &nbsp;ACTJCL</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1785</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Eleutherios,Thomas</td><td></td><td>ACT</td> <td><img class="shadow" src="../flag/act.png" alt="act" width="30" height="20"></td><td>3274020</td><td>0</td><td>1704520</td><td>1897</td></tr><tr><td>2</td><td>Cheng,Larry</td><td></td><td>ACT</td> <td><img class="shadow" src="../flag/act.png" alt="act" width="30" height="20"></td><td>3241939</td><td>0</td><td>1703050</td><td>1817</td></tr><tr><td>3</td><td>Fasakin,Olamide</td><td></td><td>ACT</td> <td><img class="shadow" src="../flag/act.png" alt="act" width="30" height="20"></td><td>3253694</td><td>0</td><td>1707751</td><td>1795</td></tr><tr><td>4</td><td>Cheng,Jerry</td><td></td><td>ACT</td> <td><img class="shadow" src="../flag/act.png" alt="act" width="30" height="20"></td><td>3244776</td><td>0</td><td>1703201</td><td>1773</td></tr><tr><td>5</td><td>Fasakin,Olaoluwa</td><td></td><td>ACT</td> <td><img class="shadow" src="../flag/act.png" alt="act" width="30" height="20"></td><td>3253708</td><td>0</td><td>1707762</td><td>1702</td></tr><tr><td>6</td><td>Selva Muthukumar,Sahasra</td><td></td><td>ACT</td> <td><img class="shadow" src="../flag/act.png" alt="act" width="30" height="20"></td><td>3265595</td><td>0</td><td>1710061</td><td>1198</td></tr><tr><td>7</td><td>MacMullin,Owen</td><td></td><td>ACT</td> <td><img class="shadow" src="../flag/act.png" alt="act" width="30" height="20"></td><td>3244253</td><td>0</td><td>1703971</td><td>1726</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">2</span> &nbsp;HBCC B</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>970</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Annapureddy,Dhruthin Reddy</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3239683</td><td>0</td><td>3194401</td><td>1263</td></tr><tr><td>2</td><td>Yang,Yifan</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3275272</td><td>0</td><td>3210840</td><td>1102</td></tr><tr><td>3</td><td>Batyrbekov,Kaisar</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3265447</td><td>0</td><td>3204363</td><td>1261</td></tr><tr><td>4</td><td>Annadasu,Shreyansh</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3275779</td><td>0</td><td>3210254</td><td>729</td></tr><tr><td>5</td><td>Batyrbekov,Aidan</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3265439</td><td>0</td><td>3203840</td><td>915</td></tr><tr><td>6</td><td>Prince,Aliza</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3283941</td><td>0</td><td>3196103</td><td>548</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">3</span> &nbsp;HBCC A</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1100</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Nguyen,Anh Kiet</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3267849</td><td>0</td><td>3206205</td><td>1400</td></tr><tr><td>2</td><td>Bodke,Krishna</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3259021</td><td>0</td><td>3202576</td><td>1247</td></tr><tr><td>3</td><td>Parker,Lucas</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>311110949</td><td>0</td><td>3209484</td><td>1509</td></tr><tr><td>4</td><td>Li,LiYuan</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3264718</td><td>0</td><td>3204551</td><td>796</td></tr><tr><td>5</td><td>Wei,Andrew</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3265277</td><td>0</td><td>3204083</td><td>990</td></tr><tr><td>6</td><td>Marasinghe,Claire</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3267822</td><td>0</td><td>3206264</td><td>660</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">4</span> &nbsp;ISCC</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>0</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Babaranda,Hasanli</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4319400</td><td>0</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Coleman, Samantha</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4323823</td><td>0</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Babaranda, Okitha</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4319613</td><td>0</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Zernov, Misha</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4323904</td><td>0</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Bennet, Seth</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4331087</td><td>0</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Cullen, Sam</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4331095</td><td>0</td><td>0</td><td>0</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">5</span> &nbsp;GCC</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>779</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Tanner,Jonathan</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>0</td><td>0</td><td>3203221</td><td>1554</td></tr><tr><td>2</td><td>Musson,Henry</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3264130</td><td>0</td><td>3203066</td><td>856</td></tr><tr><td>3</td><td>Knezevic,Milan</td><td>  </td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>0</td><td>0</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Karthick,Deepshika</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3266583</td><td>0</td><td>3204610</td><td>471</td></tr><tr><td>5</td><td>Kildea,James</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>3275167</td><td>0</td><td>3209775</td><td>1055</td></tr><tr><td>6</td><td>Li,Zhiqing</td><td></td><td>VIC</td> <td><img class="shadow" src="../flag/vic.png" alt="vic" width="30" height="20"></td><td>0</td><td>0</td><td>3214233</td><td>737</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">6</span> &nbsp;JZMC</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>804</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Collins,Immanuel</td><td></td><td>NSW</td> <td><img class="shadow" src="../flag/nsw.png" alt="nsw" width="30" height="20"></td><td>0</td><td>0</td><td>2457251</td><td>1013</td></tr><tr><td>2</td><td>Gan,Alvis</td><td></td><td>NSW</td> <td><img class="shadow" src="../flag/nsw.png" alt="nsw" width="30" height="20"></td><td>3285820</td><td>0</td><td>2459675</td><td>1450</td></tr><tr><td>3</td><td>Xie,Leo</td><td></td><td>NSW</td> <td><img class="shadow" src="../flag/nsw.png" alt="nsw" width="30" height="20"></td><td>3277631</td><td>0</td><td>2456584</td><td>1334</td></tr><tr><td>4</td><td>Tang,Talos</td><td></td><td>NSW</td> <td><img class="shadow" src="../flag/nsw.png" alt="nsw" width="30" height="20"></td><td>3277364</td><td>0</td><td>2455604</td><td>1025</td></tr><tr><td>5</td><td>Wu,Erick</td><td>  </td><td>NSW</td> <td><img class="shadow" src="../flag/nsw.png" alt="nsw" width="30" height="20"></td><td>0</td><td>0</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Mahajan,Zariya</td><td></td><td>NSW</td> <td><img class="shadow" src="../flag/nsw.png" alt="nsw" width="30" height="20"></td><td>0</td><td>0</td><td>2460272</td><td>0</td></tr></table></div></div></div>		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p> <a class="text-primary" href="http://www.vegachess.com" target="_blank">Generated by Orion</a> All rights reserved </p><p class="text-body-secondary">(Arbiter/Club : Hobsons Bay Chess Club - AUS )</p>
    </div>  </div>  </div> </div> 
  <?php include("../adsensehor.php"); ?> 
   </footer>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>  <?php include "../google.php"; ?>
</body>
</html>