<?php include "navbar.php"; ?>
<div class="d-flex flex-column">
<h2 class="mb-4">Play System</h2> <div class="table-responsive"> <table class="table table-striped"> 
 <tbody><tr><td><b>Host Federation:</b></td><td>AUS</td></tr><tr><td><b>Name of Tournament:</b></td><td>ANZAC Day Interclub Hybrid Rapid 2025</td></tr><tr><td><b>Place of Tournament:</b></td><td>Canberra, Sydney, Melbourbe, Invercargil</td></tr><tr><td><b>Starting date:</b></td><td>25/04/2025</td></tr><tr><td><b>Ending date:</b></td><td>25/04/2025</td></tr><tr><td><b>Organizer:</b></td><td>Casey Goh</td></tr><tr><td><b>Number of Rounds:</b></td><td>6</td></tr><tr><td><b>Move rate:</b></td><td>30m + 15s</td></tr><tr><td><b>Tournament Type:</b></td><td>ROUND ROBIN</td></tr><tr><td><b>Arbiter:</b></td><td>IA Shaun Press</td></tr><tr><td><b>Deputy Arbiter:</b></td><td></td></tr><tr><td><b>Program used:</b></td><td>Orion 2.3.8</td></tr></tbody></table></div></div>		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p> <a class="text-primary" href="http://www.vegachess.com" target="_blank">Generated by Orion</a> All rights reserved </p><p class="text-body-secondary">(Arbiter/Club : Hobsons Bay Chess Club - AUS )</p>
    </div>  </div>  </div> </div> 
  <?php include("../adsensehor.php"); ?> 
   </footer>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>  <?php include "../google.php"; ?>
</body>
</html>