<?php include "navbar.php"; ?>
<div class="d-flex flex-column">
<h2 class="mb-4">Schedule</h2> <div class="table-responsive"> <table class="table table-striped"> 
<thead><tr><th>Round</th><th>Time</th><th>Date</th><th>Captain time</th></tr></thead><tbody><tr class="odd"><td>1</td><td>9:30</td><td>25/04/2025</td><td>00:00 - 25/04/2025</td></tr><tr class="even"><td>2</td><td>11:00</td><td>25/04/2025</td><td>00:00 - 25/04/2025</td></tr><tr class="odd"><td>3</td><td>13:00</td><td>25/04/2025</td><td>00:00 - 25/04/2025</td></tr><tr class="even"><td>4</td><td>14:30</td><td>25/04/2025</td><td>00:00 - 25/04/2025</td></tr><tr class="odd"><td>5</td><td>16:00</td><td>25/04/2025</td><td>00:00 - 25/04/2025</td></tr></tbody></table></div></div>		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p> <a class="text-primary" href="http://www.vegachess.com" target="_blank">Generated by Orion</a> All rights reserved </p><p class="text-body-secondary">(Arbiter/Club : Hobsons Bay Chess Club - AUS )</p>
    </div>  </div>  </div> </div> 
  <?php include("../adsensehor.php"); ?> 
   </footer>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>  <?php include "../google.php"; ?>
</body>
</html>