<?php include "navbar.php"; ?>
<div class="d-flex flex-column">
<h2 class="mb-4">Team list</h2> <div class="table-responsive"> <table class="table table-striped"> 
<thead><tr><th> N </th><th>Team</th><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></tr></thead><tr><td>1</td><td>ACTJCL</td><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1785</td><td></td></tr><tr><td>2</td><td>HBCC B</td><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>970</td><td></td></tr><tr><td>3</td><td>HBCC A</td><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1100</td><td></td></tr><tr><td>4</td><td>ISCC</td><td></td><td></td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>0</td><td></td></tr><tr><td>5</td><td>GCC</td><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>779</td><td></td></tr><tr><td>6</td><td>JZMC</td><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>804</td><td></td></tr></table></div></div>		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p> <a class="text-primary" href="http://www.vegachess.com" target="_blank">Generated by Orion</a> All rights reserved </p><p class="text-body-secondary">(Arbiter/Club : Hobsons Bay Chess Club - AUS )</p>
    </div>  </div>  </div> </div> 
  <?php include("../adsensehor.php"); ?> 
   </footer>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>  <?php include "../google.php"; ?>
</body>
</html>