<?php include "navbar.php"; ?>
<div class="d-flex flex-column">
<h2 class="mb-4">Team composition</h2><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">1</span> &nbsp;HBCC A</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1753</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Annapureddy Rheyansh Reddy</td><td>FM</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3244806</td><td>2023</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Nguyen Anh Kiet</td><td>CM</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3267849</td><td>1862</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Parker Lucas</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>311110949</td><td>1787</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Bodke Krishna</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3259021</td><td>1714</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Batyrbekov Kaisar</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3265447</td><td>1667</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Venkat Nyra</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3286410</td><td>1465</td><td>0</td><td>0</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">2</span> &nbsp;ACTJCL A</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1815</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Fasakin Olamide</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3253694</td><td>1892</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Macmullin Owen</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3244253</td><td>1883</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Horikawa Masaki</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3243931</td><td>1878</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Hegde Sanat</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3265471</td><td>1826</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Lee Nicholas</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3250679</td><td>1801</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Selva Muthukumar Sahasra</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3265595</td><td>1612</td><td>0</td><td>0</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">3</span> &nbsp;HBCC B</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1589</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Ramanathan Ashwin</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3275221</td><td>1711</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Annapureddy Dhruthin Reddy</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3239683</td><td>1675</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Batyrbekov Aidan</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3265439</td><td>1575</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Wei Andrew</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3265277</td><td>1658</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Jyothi Nikhil Neev</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3284670</td><td>1459</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Marasinghe Claire</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3267822</td><td>1457</td><td>0</td><td>0</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">4</span> &nbsp;ACTJCL B</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1670</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Cheng Jerry</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3244776</td><td>1788</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Fasakin Olaoluwa</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3253708</td><td>1782</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Padma Yonten Gyalpo</td><td> </td><td>BHU</td> <td><img class="shadow" src="../flag/bhu.png" alt="bhu" width="30" height="20"></td><td>17501245</td><td>1770</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Vinothkumar Nivin</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3265269</td><td>1605</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Vangala Abhinav</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3278662</td><td>1546</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Mididuddi Varshini</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3276724</td><td>1528</td><td>0</td><td>0</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">5</span> &nbsp;Geelong Chess Club</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1411</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Musson Henry</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3264130</td><td>1463</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Kildea, James</td><td>  </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3275167</td><td>0</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Thakur, Ishaan</td><td>  </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>0</td><td>0</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Ditchfield, Leo</td><td>  </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>0</td><td>0</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Simner, Oliver</td><td>  </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>0</td><td>0</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Jin, Audrey</td><td>  </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>0</td><td>0</td><td>0</td><td>0</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">6</span> &nbsp;Teh Chess Academy</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1774</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Teh Rui Gen</td><td>FM</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>5749476</td><td>1886</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Harris Eamon</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3258505</td><td>1844</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Le Quang Minh</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3288323</td><td>1804</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Huang Yuqi (ricky)</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3268250</td><td>1628</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Liyanage Nithuli</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3266729</td><td>1798</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Ho Gia Bao</td><td> </td><td>VIE</td> <td><img class="shadow" src="../flag/vie.png" alt="vie" width="30" height="20"></td><td>12433187</td><td>1684</td><td>0</td><td>0</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">7</span> &nbsp;Invercargill Southland Chess Club</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>1534</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Zernov Misha</td><td> </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4323904</td><td>1598</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Coleman Samantha</td><td> </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4323823</td><td>1669</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Babaranda Hasanli</td><td> </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4319400</td><td>1663</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Babaranda Okitha</td><td> </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4319613</td><td>1476</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Bennet, Seth</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4331087</td><td>0</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Villanueva, Andrei Martin</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4333551</td><td>0</td><td>0</td><td>0</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">8</span> &nbsp;Kapiti Chess Club</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>1446</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Fitton Stanley</td><td> </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4329724</td><td>1676</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Millar Wakefield</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4334450</td><td>0</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Heta, Isaiah</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4333063</td><td>0</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Jingwei Xu</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4331389</td><td>0</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Patterson,James</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4326768</td><td>0</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Moore, George</td><td>  </td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>4333098</td><td>0</td><td>0</td><td>0</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">9</span> &nbsp;JZMC</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>1772</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Wang Daniel</td><td>CM</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3238873</td><td>1971</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Gong Leo</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3266192</td><td>1887</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Jiang Benjamin Wise</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3241971</td><td>1846</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Li Baize</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3274772</td><td>1730</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Wang Caleb</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3238881</td><td>1632</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Mahajan Zariya</td><td> </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3290751</td><td>1564</td><td>0</td><td>0</td></tr><tr><td>7</td><td>Goh,Casey</td><td>  </td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>3251098</td><td>0</td><td>0</td><td>0</td></tr></table></div></div><div class="card mb-3"
>  <div class="card-header"> <h3> <span class="badge bg-secondary">10</span> &nbsp;KCE18</h3></div>
<div class="table-responsive">  
<table class="table"><thead><tr><th>Origin</th><th>Region</th><th colspan="2">Fed</th><th>Rtg</th><th>Captain</th></thead><tr><td></td><td></td><td>MAS</td> <td><img class="shadow" src="../flag/mas.png" alt="mas" width="30" height="20"></td><td>1533</td><td></td></tr></table><table class="table table-striped"><thead><tr><th>Bo.</th><th>Player</th><th>T</th><th colspan="2">Fed</th><th>ID FIDE</th><th>FRtg</th><th>ID Nat</th><th>NRtg</th></tr></thead><tr><td>1</td><td>Noor Hazlan Muhd Nur Hazim</td><td> </td><td>MAS</td> <td><img class="shadow" src="../flag/mas.png" alt="mas" width="30" height="20"></td><td>35836970</td><td>1668</td><td>0</td><td>0</td></tr><tr><td>2</td><td>Mohd Nurul Izani Muhd Irzam D</td><td> </td><td>MAS</td> <td><img class="shadow" src="../flag/mas.png" alt="mas" width="30" height="20"></td><td>5734134</td><td>1496</td><td>0</td><td>0</td></tr><tr><td>3</td><td>Azha Syahril Asyraf Firdaus</td><td> </td><td>MAS</td> <td><img class="shadow" src="../flag/mas.png" alt="mas" width="30" height="20"></td><td>35859857</td><td>1573</td><td>0</td><td>0</td></tr><tr><td>4</td><td>Khaireza Dani Azeem</td><td> </td><td>MAS</td> <td><img class="shadow" src="../flag/mas.png" alt="mas" width="30" height="20"></td><td>35827238</td><td>1459</td><td>0</td><td>0</td></tr><tr><td>5</td><td>Khaireza, Daania Adeena</td><td>  </td><td>MAS</td> <td><img class="shadow" src="../flag/mas.png" alt="mas" width="30" height="20"></td><td>35844779</td><td>0</td><td>0</td><td>0</td></tr><tr><td>6</td><td>Mohd Nurul Izani Kaseh Irsya</td><td> </td><td>MAS</td> <td><img class="shadow" src="../flag/mas.png" alt="mas" width="30" height="20"></td><td>5730929</td><td>1602</td><td>0</td><td>0</td></tr></table></div></div></div>		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p> <a class="text-primary" href="http://www.vegachess.com" target="_blank">Generated by Orion</a> All rights reserved </p><p class="text-body-secondary">(Arbiter/Club : Hobsons Bay Chess Club - AUS )</p>
    </div>  </div>  </div> </div> 
   </footer>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script></body>
</html>