<?php include "navbar.php"; ?>
<div class="d-flex flex-column"> 
   <h2 class="mb-4">Team Standings</h2>     <div class="flex flex-column mb-4">   	  <script src="rankteam.js"></script>
   <h4 class="mb-4">standings at round 8</h4><div class="table-responsive mb-3 pt-4"> <table class="table table-striped">
<thead><tr><th>Rk</th><th>N</th><th>Team</th><th colspan="2">Fed</th><th>G</th><th><span class="badge text-bg-success">+ = -</span></th><th>Pts</th><th>GP</th><th>Dir_MP</th><th>EMGSB</th></tr></thead><tbody><tr><td>1</td><td>9</td><td>JZMC</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>8</td><td>7 1 0</td><td class="score">15</td><td>35.5</td><td>0</td><td>207</td></tr><tr><td>2</td><td>6</td><td>Teh Chess Academy</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>8</td><td>7 0 1</td><td class="score">14</td><td>35</td><td>0</td><td>196.5</td></tr><tr><td>3</td><td>2</td><td>ACTJCL A</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>8</td><td>6 1 1</td><td class="score">13</td><td>36.5</td><td>0</td><td>242.5</td></tr><tr><td>4</td><td>1</td><td>HBCC A</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>8</td><td>5 1 2</td><td class="score">11</td><td>32</td><td>0</td><td>179.5</td></tr><tr><td>5</td><td>4</td><td>ACTJCL B</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>8</td><td>5 1 2</td><td class="score">11</td><td>28.5</td><td>0</td><td>132</td></tr><tr><td>6</td><td>10</td><td>KCE18</td><td>MAS</td> <td><img class="shadow" src="../flag/mas.png" alt="mas" width="30" height="20"></td><td>8</td><td>3 0 5</td><td class="score">6</td><td>22.5</td><td>0</td><td>167.5</td></tr><tr><td>7</td><td>3</td><td>HBCC B</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>8</td><td>2 0 6</td><td class="score">4</td><td>17.5</td><td>0</td><td>104</td></tr><tr><td>8</td><td>8</td><td>Kapiti Chess Club</td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>8</td><td>2 0 6</td><td class="score">4</td><td>15</td><td>0</td><td>54.5</td></tr><tr><td>9</td><td>7</td><td>Invercargill Southland Chess Club</td><td>NZL</td> <td><img class="shadow" src="../flag/nzl.png" alt="nzl" width="30" height="20"></td><td>8</td><td>1 0 7</td><td class="score">2</td><td>11.5</td><td>0</td><td>70</td></tr><tr><td>10</td><td>5</td><td>Geelong Chess Club</td><td>AUS</td> <td><img class="shadow" src="../flag/aus.png" alt="aus" width="30" height="20"></td><td>8</td><td>0 0 8</td><td class="score">0</td><td>6</td><td>0</td><td>36</td></tr></tbody></table></div>  </div>
<div class="card">
  <div class="card-body">
  <h5 class="card-title mb-4">TieBreak legend: </h5><p class="card-text mb-2"><strong>GP</strong>: Game Points</p><p class="card-text mb-2"><strong>Dir_MP</strong>: Direct Encounter MP (all play all)</p><p class="card-text mb-2"><strong>EMGSB</strong>: Sonneborn-Berger: MP x GP (*)</p></div>
</div>
</div>
		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p> <a class="text-primary" href="http://www.vegachess.com" target="_blank">Generated by Orion</a> All rights reserved </p><p class="text-body-secondary">(Arbiter/Club : Hobsons Bay Chess Club - AUS )</p>
    </div>  </div>  </div> </div> 
   </footer>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script></body>
</html>