name: Sync FTP to Local and Commit

on:
  schedule:
    - cron: "1/5 0 * * *" # Runs the action every day at midnight (UTC)
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync-ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install lftp
        run: |
          sudo apt update
          sudo apt install lftp

      - name: Sync FTP to Local
        run: |
          lftp -e 'mirror --parallel=20 -c  htdocs www;quit'  -u $FTP_USER,$FTP_PASSWORD ftp://ftpupload.net
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      - name: Commit changes
        run: |
          git config --global user.name "FTP Sync"
          git config --global user.email "ftp@hbcc.com"
          git add .
          git commit -m "Sync FTP changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
