name: Sync FTP to Local and Commit

on:
  schedule:
    - cron: "*/5 * * * *" # Runs the action every day at midnight (UTC)
  push:
    paths:
      - .github/workflows/sync.yml
      - src/*.*
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  sync-ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
            
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install lftp rename
          npm install
      - name: Descrypt vault files
        run: |
          node src/vault.mjs decrypt
        env:
          VAULT_SECRET: ${{secrets.VAULT_SECRET}}
      - name: Keep site alive
        continue-on-error: true
        run: |
          node src/bytehost.mjs
          
      - name: "Fetch content from ftp server"
        uses: "samuraitruong/use-ftp-action@main"
        with: 
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_ROOT_FOLDER: htdocs
          LOCAL_FOLDER: 'wwwftp'
          FTP_HOST: ftp://ftpupload.net
          SYNC_MODE: download
          

      # - name: Sync FTP to Local
      #   run: |
      #     lftp -e 'mirror --parallel=20 --ignore-time -c  htdocs www;quit'  -u $FTP_USER,$FTP_PASSWORD ftp://ftpupload.net
      #     find www -type f -name "*.php" -exec bash -c '
      #     for file; do
      #         cp -f "$file" "${file%.php}.html"
      #     done' bash {} +
          
      #   env:
      #     FTP_USER: ${{ secrets.FTP_USER }}
      #     FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      - name: Update HTML content
        run: |
          cp -r wwwftp/* www
          docker compose up -d
          sleep 2
          sudo chown -R $(whoami) ./www
          node src/update-html.mjs
          docker compose down
      - name: run Sync.mjs

        run: |
          sudo chown -R $(whoami) ./www
          node src/sync.mjs

      - name: Replace PHP links with HTML links
        run: |
          DIRECTORY="./www"

          find "$DIRECTORY" -type f -name "*.html" -print0 | while IFS= read -r -d '' file; do
            sed -i 's/\.php/.html/g' "$file"
          done
          find "$DIRECTORY" -type f -name "*.js" -print0 | while IFS= read -r -d '' file; do
            sed -i 's/\.php/.html/g' "$file"
          done
      - name: Commit changes
        id: commit
        run: |
          sudo chown -R $(whoami) ./wwwftp
          rm -rf wwwftp
          find "www" -type f -name '*~*' -exec rm -f {} +
          rm www/.html || true
          git status
          if [[ -n $(git status --porcelain) ]]; then

            git config --global user.name "FTP Sync"
            git config --global user.email "ftp@hbcc.com"
            git add .
            git commit -am "Sync FTP changes"
            git push
            echo "CHANGED=true" >> "$GITHUB_OUTPUT"

          else
            echo "There are no changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        if: steps.commit.outputs.CHANGED == 'true'
        uses: actions/configure-pages@v4
      - name: Upload artifact
        if: steps.commit.outputs.CHANGED == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./www"
      - name: Deploy to GitHub Pages
        if: steps.commit.outputs.CHANGED == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
        
