name: Sync FTP to Local and Commit

on:
  schedule:
    - cron: "*/5 * * * *" # Runs the action every day at midnight (UTC)
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  sync-ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install lftp
        run: |
          sudo apt update
          sudo apt install lftp

      - name: Sync FTP to Local
        run: |
          lftp -e 'mirror --parallel=20 --ignore-time -c  htdocs www;quit'  -u $FTP_USER,$FTP_PASSWORD ftp://ftpupload.net
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: Commit changes
        id: commit
        run: |
          git status
          if [[ -n $(git status --porcelain) ]]; then

            git config --global user.name "FTP Sync"
            git config --global user.email "ftp@hbcc.com"
            git add .
            git commit -am "Sync FTP changes"
            git push
            echo "CHANGED=true" >> "$GITHUB_OUTPUT"

          else
            echo "There are no changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        if: steps.commit.outputs.CHANGED == 'true'
        uses: actions/configure-pages@v4
      - name: Upload artifact
        if: steps.commit.outputs.CHANGED == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./www"
      - name: Deploy to GitHub Pages
        if: steps.commit.outputs.CHANGED == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
